import DATABASE_TABLES from './DatabaseTables';
import APP_NAVIGATION from './AppNavigation';
import {
  CATEGORIAS_ICONS,
  CATEGORIAS_ICON_COLORS,
  TRANSACTION_STATES,
  TXN_CODES,
  TXN,
} from './TaecelConfig';
import {PRINT_TABLE_HEADER, PRINT_TABLE} from './PrintingConfig';
import {LOGOS_URL, TKP_LOGO_URL} from './Urls';
import {
  LOGO_MAGICO_BASE64,
  LOGO_BASE64,
  MELATERR_LOGO,
  MELATERR_LOGO2,
  CHISPAZO_LOGO,
} from './LogosBase64';

export {
  DATABASE_TABLES,
  APP_NAVIGATION,
  CATEGORIAS_ICONS,
  CATEGORIAS_ICON_COLORS,
  PRINT_TABLE_HEADER,
  PRINT_TABLE,
  TRANSACTION_STATES,
  TXN_CODES,
  LOGOS_URL,
  LOGO_MAGICO_BASE64,
  LOGO_BASE64,
  MELATERR_LOGO,
  MELATERR_LOGO2,
  CHISPAZO_LOGO,
  TKP_LOGO_URL,
  TXN,
};
